name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Release, Debug]
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Set up compiler
      if: matrix.compiler == 'clang'
      run: |
        sudo apt-get install -y clang clang++

    - name: Clean build directory
      run: |
        rm -rf build
        mkdir -p build

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S .

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Basic Shell Tests
      run: |
        echo "exit" | ./build/UnixShell
        echo "quit" | ./build/UnixShell

    - name: Test
      working-directory: build
      run: ctest --build-config ${{ matrix.build_type }} --output-on-failure
